siteConfig:
    title: John's internet house
    author: John Whiles
    url: https://johnwhiles.com # Required
plugins:
  - resolve: saber-plugin-query-posts
  - resolve: saber-plugin-feed
    options:
      atomFeed: true
      rss2Feed: true
      jsonFeed: true
